import Link from "next/link"
import { ShieldAlert, ExternalLink } from "lucide-react"

export function Footer() {
  return (
    <footer className="w-full border-t border-stone-200 dark:border-stone-800 bg-stone-50/50 dark:bg-stone-900/40 mt-16 py-10">
      <div className="max-w-6xl mx-auto px-4 flex flex-col gap-6">
        <div className="flex items-start gap-3 p-4 rounded-xl border border-amber-200 dark:border-amber-900/50 bg-amber-50/60 dark:bg-amber-950/20 text-amber-900 dark:text-amber-200 text-xs sm:text-sm">
          <ShieldAlert className="w-5 h-5 shrink-0 text-amber-600 dark:text-amber-400 mt-0.5" />
          <p>
            <strong className="font-semibold">Important Pricing Disclaimer:</strong> All simulated
            subscription rates and volume discounts generated by the AI Deal Agent are{" "}
            <strong>reference suggestions for group negotiation, not formal commercial offers</strong>.
            Final pricing, meal delivery timings, and trial policies are subject to direct mutual
            agreement with the independent tiffin provider.
          </p>
        </div>

        <div className="flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-stone-500 dark:text-stone-400">
          <p>© 2026 MessMate. Built with FastAPI, LangGraph, Next.js, and TanStack Query.</p>
          <div className="flex items-center gap-4">
            <Link href="/about" className="hover:underline">
              Multi-Agent Architecture
            </Link>
            <Link href="/onboard" className="hover:underline">
              Provider Portal
            </Link>
            <a
              href="https://github.com/bleedZzzz/messmate"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1 hover:underline"
            >
              Repository <ExternalLink className="w-3 h-3" />
            </a>
          </div>
        </div>
      </div>
    </footer>
  )
}
